on:
  pull_request:
    branches: [master, next]

name: verify

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2.3
        ports:
          - 6379:6379

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CORVA_NPMJS_PUBLIC_TOKEN }}
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run audit
        run: npm audit --omit=dev

      - name: Run lint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error

      - name: Run unit tests
        run: npm run test:unit --if-present

      - name: Run e2e tests
        run: npm run test:e2e
